version: "3"

services: 
    rest-api:
        image: rest-api:1.0
        container_name: api
        environment:
            - REDIS=1
        ports: 
            - "8080:8080"
        links: 
            - redis
    redis:
        image: redis:6-alpine
        container_name: rd
        ports: 
            - "6379:6379"